version: '3.0'

services:
  sonarqube:
    image: sonarqube:lts
    container_name: sonarqube
    ports:
      - 9000:9000
  
  backend:
    build: ./backend
    container_name: customer-backend
    ports:
      - 8181:8080
    links:
      - sonarqube
      
  frontend:
    build: ./frontend
    container_name: customer-frontend
    ports:
      - 4111:80


